"""Scientific utilities for the Umbra Vandenberg SAR analysis."""

from .cross_spectrum import (
    CROSS_SPECTRUM_CONVENTION,
    intensity,
    spatial_cross_spectrum,
    wrapped_phase_error,
)
from .subaperture import (
    ApertureDurations,
    AxisConvention,
    MetadataError,
    ProcessedSupport,
    SicdSubapertureContext,
    SubapertureBand,
    WindowMetrics,
    image_to_shifted_spectrum,
    make_window,
    masked_spectrum,
    plan_band,
    plan_centered_band,
    plan_tiled_bands,
    rectangular_partition,
    shifted_spectrum_to_image,
    sublook_from_spectrum,
    sublook_metadata,
)
from .wave_analysis import (
    axial_difference_deg,
    detrend_and_window_intensity,
    find_peak_candidates,
    intensity_spectrum_crop,
    match_stable_peak,
    phase_correlation_shift,
    physical_frequency_grid,
    wrap_phase,
)

__all__ = [
    "ApertureDurations",
    "AxisConvention",
    "CROSS_SPECTRUM_CONVENTION",
    "MetadataError",
    "ProcessedSupport",
    "SicdSubapertureContext",
    "SubapertureBand",
    "WindowMetrics",
    "image_to_shifted_spectrum",
    "intensity",
    "make_window",
    "masked_spectrum",
    "plan_band",
    "plan_centered_band",
    "plan_tiled_bands",
    "rectangular_partition",
    "shifted_spectrum_to_image",
    "spatial_cross_spectrum",
    "sublook_from_spectrum",
    "sublook_metadata",
    "wrapped_phase_error",
    "axial_difference_deg",
    "detrend_and_window_intensity",
    "find_peak_candidates",
    "intensity_spectrum_crop",
    "match_stable_peak",
    "phase_correlation_shift",
    "physical_frequency_grid",
    "wrap_phase",
]
